### ISSUE TITLE
Error when sending reply

### ISSUE THREAD

**Issue by dmarlow** [dotnetprojects/sharp-dhcp-server-lib#5]
I'm getting this error when doing this: `dhcpRequest.SendDHCPReply(DHCPMsgType.DHCPOFFER, ip, replyOptions);`

I'm binding to `0.0.0.0` and receiving requests just fine.
```
System.Net.Sockets.SocketException (0x80004005): Only one usage of each socket address (protocol/network address/port) is normally permitted
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.UdpClient..ctor(Int32 port, AddressFamily family)
   at System.Net.Sockets.UdpClient..ctor(Int32 port)
   at DotNetProjects.DhcpServer.DHCPRequest.SendDHCPReply(DHCPMsgType msgType, IPAddress ip, DHCPReplyOptions replyData, Dictionary`2 otherForceOptions, IEnumerable`1 forceOptions) in C:\projects\sharp-dhcp-server-lib\SharpDHCPServerLib\DHCPRequest.cs:line 331
   at DotNetProjects.DhcpServer.DHCPRequest.SendDHCPReply(DHCPMsgType msgType, IPAddress ip, DHCPReplyOptions replyData) in C:\projects\sharp-dhcp-server-lib\SharpDHCPServerLib\DHCPRequest.cs:line 259
```

**Comment by dmarlow** [comment]
Works great on latest now. Thanks!
